#!/bin/bash
# --------------------------------------------------------------------------
# This script installs files and services specific to this project.
#
# Author: Bernhard Bablok
# License: GPL3
#
# Website: https://github.com/bablokb/cm4io_rtcctl
#
# --------------------------------------------------------------------------

PACKAGES="python3-arrow python3-smbus"

# --- basic packages   ------------------------------------------------------

check_packages() {
  local p
  for p in "$@"; do
    echo -en "Checking $p ... " >&2
    dpkg -s "$p" 2>/dev/null | grep -q "Status.*ok" || return 0
    echo "ok" >&2
  done
  return 1
}

install_packages() {
  if [ -n "$PACKAGES" ] && check_packages $PACKAGES; then
    echo -e "[INFO] installing additional packages" 2>&1
    apt-get update
    apt-get -y install $PACKAGES
  fi
}

# --- install specific files   ----------------------------------------------

install_files() {
  echo -e "[INFO] installing project files" 2>&1

  for f in `find $(dirname "$0")/../files/ -type f`; do
    cp "$f" "${f#*files}"
    chown root:root "${f#*files}"
  done

  chmod 755 /usr/local/sbin/cm4io_rtcctl.py
  chmod 644 /usr/local/sbin/pcf85063a.py
  chmod 644 /etc/systemd/system/cm4io_rtcctl.service
}

# --- configure system   ----------------------------------------------------

configure_system() {
  if ! grep -q "^dtparam=i2c_arm=on" /boot/config.txt; then
    echo -e "[INFO] configuring /boot/config.txt" 2>&1
    echo "dtparam=i2c_arm=on" >> /boot/config.txt
  fi

  if ! grep -q "^dtparam=i2c_vc=on" /boot/config.txt; then
    echo -e "[INFO] configuring /boot/config.txt" 2>&1
    echo "dtparam=i2c_vc=on" >> /boot/config.txt
  fi

  if grep -q "^dtoverlay=i2c-rtc,pcf85063a" /boot/config.txt; then
    echo -e "[INFO] configuring /boot/config.txt" 2>&1
    sed -i -e 's/dtoverlay=i2c-rtc,pcf85063a/#dtoverlay=i2c-rtc,pcf85063a/' /boot/config.txt
  fi

  if ! grep -q "^i2c-dev" /etc/modules; then
    echo -e "[INFO] configuring /etc/modules" 2>&1
    echo "i2c-dev" >> /etc/modules
  fi
}

# --- activate service   ----------------------------------------------------

enable_services() {
  echo -e "[INFO] enabeling cm4io_rtcctl.service" 2>&1
  systemctl enable cm4io_rtcctl.service
}

# --- main program   --------------------------------------------------------

install_packages
install_files
configure_system
enable_services
echo "Restart the system to activate changes"
